name: workshop_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  crypto: ^3.0.1
  corsac_jwt: ^1.0.0-nullsafety.1
  dart_jsonwebtoken: ^2.4.2
  jaguar_jwt: ^3.0.0
  mysql1: ^0.20.0
  shelf_hotreload: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
